MERGE INTO public.RATING (RATING_ID, NAME) VALUES (1, 'G');
MERGE INTO public.RATING (RATING_ID, NAME) VALUES (2, 'PG');
MERGE INTO public.RATING (RATING_ID, NAME) VALUES (3, 'PG13');
MERGE INTO public.RATING (RATING_ID, NAME) VALUES (4, 'R');
MERGE INTO public.RATING (RATING_ID, NAME) VALUES (5, 'NC17');

MERGE INTO public.GENRE (GENRE_ID, NAME) VALUES (1, 'COMEDY');
MERGE INTO public.GENRE (GENRE_ID, NAME) VALUES (2, 'DRAMA');
MERGE INTO public.GENRE (GENRE_ID, NAME) VALUES (3, 'CARTOON');
MERGE INTO public.GENRE (GENRE_ID, NAME) VALUES (4, 'THRILLER');
MERGE INTO public.GENRE (GENRE_ID, NAME) VALUES (5, 'DOCUMENTARY');
MERGE INTO public.GENRE (GENRE_ID, NAME) VALUES (6, 'ACTION');